<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm 2-Factor Authentication</title>
    <link rel="stylesheet" href="{{ asset('css/styleEnter2fa.css') }}">
</head>

<body>
    <div class="container">
        <h2>Enter 2FA code</h2>
        <h3>Enter the code generated by your authenticator</h3>
        <div class="input-container">
            <input type="text" id="code2fa" placeholder="XXX-XXX" maxlength="7" oninput="format2fa(this)">
        </div>
        <div class="button-container">
            <button class="button" onclick="verify()">Confirm</button>
            <button class="button" onclick="cancel2FA()">Cancel</button>
        </div>
    </div>
    <script>
        const apiVerify = 'http://localhost:3000/api/Accounts/verify-2fa';
        const apiDisable = 'http://localhost:3000/api/Accounts/disable-2fa';

        function format2fa(input) {
            let digits = input.value.replace(/\D/g, '').substring(0, 6); // Maks 6 digit

            // Format sebagai XXX-XXX jika panjang > 3
            if (digits.length > 3) {
                input.value = digits.slice(0, 3) + '-' + digits.slice(3);
            } else {
                input.value = digits;
            }
        }

        async function verify() {
            const codeInput = document.getElementById('code2fa').value.replace('-', ''); // ambil input, hilangkan strip
            console.log(codeInput);
            if (codeInput.length !== 6) {
                alert('Please enter a 6-digit 2FA code');
                return;
            }

            try {
                const response = await fetch(apiVerify, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        email: 'haritswot@gmail.com', // HARDCODE
                        token: codeInput
                    })
                });

                if (!response.ok) {
                    // Jika status HTTP bukan 2xx, lempar error
                    const errorData = await response.json();
                    throw new Error(errorData.message || 'Failed to verify 2FA code');
                }

                alert('2FA verified successfully!');
                window.location.href = '/dashboard';

            } catch (error) {
                // Tangani error disini
                alert('Error verifying 2FA: ' + error.message);
                console.error('Verify 2FA error:', error);
            }
        }

        async function cancel2FA() {
            if (!confirm('Are you sure you want to cancel 2FA activation?')) return;

            try {
                const response = await fetch(apiDisable, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        email: 'haritswot@gmail.com'
                    })
                });

                const result = await response.json();
                if (!response.ok) {
                    throw new Error(result.error || 'Failed to disable 2FA');
                }

                alert('2FA has been disabled.');
                window.location.href = '/profile'; // Atau redirect ke halaman lain
            } catch (error) {
                alert('Error disabling 2FA: ' + error.message);
                console.error('Disable 2FA error:', error);
            }
        }
    </script>
</body>

</html>