<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm 2-Factor Authentication</title>
    <link rel="stylesheet" href="<?php echo e(asset('css/styleEnter2fa.css')); ?>">
</head>

<body>
    <div class="container">
        <h2>Enter 2FA code</h2>
        <h3>Enter the code generated by your authenticator</h3>
        <div class="input-container">
            <input type="text" id="code2fa" placeholder="XXX-XXX" maxlength="7" oninput="format2fa(this)">
        </div>
        <div class="button-container">
            <button class="button" onclick="verify()">Confirm</button>
        </div>
    </div>
    <script>
        const api = 'http://localhost:3000/api/Accounts/verify-2fa';

        function format2fa(input) {
            let digits = input.value.replace(/\D/g, '').substring(0, 6); // Maks 6 digit

            // Format sebagai XXX-XXX jika panjang > 3
            if (digits.length > 3) {
                input.value = digits.slice(0, 3) + '-' + digits.slice(3);
            } else {
                input.value = digits;
            }
        }

        async function verify() {
            const codeInput = document.getElementById('code2fa').value.replace('-', ''); // ambil input, hilangkan strip
            console.log(codeInput);
            if (codeInput.length !== 6) {
                alert('Please enter a 6-digit 2FA code');
                return;
            }

            try {
                const response = await fetch(api, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        email: 'haritswot@gmail.com', // HARDCODE
                        token: codeInput
                    })
                });

                if (!response.ok) {
                    // Jika status HTTP bukan 2xx, lempar error
                    const errorData = await response.json();
                    throw new Error(errorData.message || 'Failed to verify 2FA code');
                }

                const data = await response.json();
                alert('2FA verified successfully!');
                // Lanjutkan proses setelah sukses, misal redirect ke dashboard

            } catch (error) {
                // Tangani error disini
                alert('Error verifying 2FA: ' + error.message);
                console.error('Verify 2FA error:', error);
            }
        }
    </script>
</body>

</html><?php /**PATH C:\Users\harit\OneDrive\Documents\GitHub\WebStudyIT\resources\views/auth/enterTwoFactor.blade.php ENDPATH**/ ?>