<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify 2-Factor Authentication</title>
    <link rel="stylesheet" href="<?php echo e(asset('css/styleverif2fa.css')); ?>">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <div class="verify2fa-container">
        <h1>Enter Your Verification Code</h1>
        <h3>Enter the code generated by your authenticator</h3>

        <form id="verify2faForm">
            <div class="input-container">
                <input type="text" id="code2fa" placeholder="XXX-XXX" maxlength="7" oninput="format2fa(this)" required>
            </div>
            <button class="button" type="submit">Enter</button>
        </form>
    </div>

    <script>
        const apiVerify2faUrl = 'http://localhost:3000/api/Accounts/verify-2fa';

            const email = localStorage.getItem('userEmail');

        function format2fa(input) {
            let digits = input.value.replace(/\D/g, '').substring(0, 6); // Maks 6 digit

            // Format sebagai XXX-XXX jika panjang > 3
            if (digits.length > 3) {
                input.value = digits.slice(0, 3) + '-' + digits.slice(3);
            } else {
                input.value = digits;
            }
        }

        const userId = localStorage.getItem('userId');
        const userType = localStorage.getItem('userType');

        if (!userId || !userType) {
            Swal.fire({
                icon: 'warning',
                title: 'Session expired',
                text: 'Please login again.',
            }).then(() => {
                window.location.href = '/login';
            });
        }

        document.getElementById('verify2faForm').addEventListener('submit', async function(e) {
            e.preventDefault();

            const codeRaw = document.getElementById('code2fa').value;
            const code = codeRaw.replace('-', ''); // Remove dash if any

            try {
                const response = await fetch(apiVerify2faUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ email, token: code })
                });

                if (response.ok) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Verification Successful',
                        text: 'Redirecting to your dashboard...',
                        timer: 2000,
                        showConfirmButton: false
                    }).then(() => {
                        if (userType === 'Admin') {
                            window.location.href = `/admin/${userId}/dashboard`;
                        } else if (userType === 'Free' || userType === 'Subscriber') {
                            window.location.href = `/students/${userId}/dashboard`;
                        } else {
                            Swal.fire('Unknown User Type', '', 'error');
                        }
                    });
                } else {
                    const error = await response.json();
                    Swal.fire({
                        icon: 'error',
                        title: 'Verification Failed',
                        text: error.message || 'Invalid code',
                    });
                }
            } catch (err) {
                console.error(err);
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'Error verifying 2FA',
                });
            }
        });
    </script>
</body>
</html>
<?php /**PATH C:\Users\harit\OneDrive\Documents\GitHub\WebStudyIT\resources\views/Auth/verify2fa.blade.php ENDPATH**/ ?>